"""Append the MEASURED glide-entry pose to the curriculum poses file.

The assisted curriculum stages can only start from a named measured pose. Training
the glide itself therefore needs a pose recorded at the moment loaded left-only
support first holds, with the episode's phase already advanced into the hold.

This tool takes the output of `local/measure-glide-pose.py`, clamps the median
joint configuration to the model's own joint ranges (two joints measured a few
thousandths of a radian outside theirs), and rewrites the poses file in exactly the
format it already uses. It refuses to touch the file unless a plain re-emit of the
current contents reproduces it byte for byte, so no unrelated formatting is lost.
"""
import argparse
import json
import pprint
from pathlib import Path

import mujoco

ROOT = Path(__file__).resolve().parents[1]
POSE_FILE = ROOT/'src/mjlab_microduck/tasks/microduck_onefoot_curriculum_poses.py'
MODEL = ROOT/'src/mjlab_microduck/robot/microduck/robot_groundcontact_rollers.xml'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--measurement', type=Path, required=True)
    parser.add_argument('--name', default='glide')
    parser.add_argument('--dry-run', action='store_true')
    a = parser.parse_args()
    measurement = json.loads(a.measurement.read_text())
    source = POSE_FILE.read_text()
    namespace = {}
    exec(source, namespace)                                  # noqa: S102 - local data file
    poses = namespace['POSES']
    if a.name in poses:
        raise SystemExit(f'{a.name} already exists; refusing to overwrite a measured pose')
    # Guard the formatting contract before writing anything.
    if source.split('POSES = ', 1)[1].rstrip() != pprint.pformat(
            poses, width=100, sort_dicts=False).rstrip():
        raise SystemExit('Poses file no longer round-trips; refusing to rewrite it')

    model = mujoco.MjModel.from_xml_path(str(MODEL))
    margin = 1e-4                       # the pose test requires STRICTLY inside the range
    pose, clamped = {}, {}
    for name, value in measurement['median_pose'].items():
        low, high = model.jnt_range[model.joint(name).id]
        fixed = min(max(value, low+margin), high-margin)
        pose[name] = float(fixed)
        if fixed != value:
            clamped[name] = dict(measured=value, clamped=float(fixed),
                                 lower=float(low), upper=float(high))
    if set(pose) != set(list(poses.values())[0]['pose']):
        raise SystemExit('Measured pose joint set does not match the existing poses')
    # Ground on the tyre MESH vertices, exactly as tests/test_onefoot_curriculum.py
    # does. The left skate ends up on the ground and the swing skate stays lifted by
    # whatever the measured single-support configuration dictates.
    lowest = measurement['lowest_wheel_mesh_min_z']
    # Restore the measured servo velocities and root pitch too: spawning the
    # glide-entry POSTURE with every joint at rest and a level root is a state that
    # never occurs in a real trajectory.
    joint_vel = {name: float(value) for name, value in measurement['median_all_joint_vel'].items()}
    poses[a.name] = dict(root_z=float(-lowest),
                         root_roll=float(measurement['roll']['p50']),
                         root_pitch=float(measurement['pitch']['p50']),
                         pose=pose, joint_vel=joint_vel)
    if not a.dry_run:
        POSE_FILE.write_text('"""Measured mesh-grounded spawn poses; NOT equilibrium controllers.\n'
                             '\nGenerated by local/solve-onefoot-curriculum-poses.py; the glide\n'
                             'entry pose is appended from local/measure-glide-pose.py.\n"""\n\n'
                             'POSES = '+pprint.pformat(poses, width=100, sort_dicts=False)+'\n')
    print('GLIDE_POSE_ADDED', json.dumps(dict(name=a.name, root_z=poses[a.name]['root_z'],
          root_roll=poses[a.name]['root_roll'], clamped=clamped, dry_run=a.dry_run,
          swing_lift=measurement['swing_lift'], speed=measurement['speed']),
          ensure_ascii=False))


if __name__ == '__main__':
    main()
